name: Create a GitHub Release
author: John-John Tedro
description: Create a GitHub Release with sensible defaults.

inputs:
  token:
    description: Github token to use, set by you to `{{secrets.GITHUB_TOKEN}}`.
    required: true
  name:
    description: Name of release to create. `nightly` forces the `nightly` tag to update.
    required: true
  files:
    description: Glob list of files to publish. Such as `dist/*`.
    required: true
  sha:
    description: The SHA reference that the created release will be pointed to.
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
